### ISSUE TITLE
Time data type causes error with Mysql Workbench 6.2

### ISSUE THREAD

**Issue by JDruery** [johmue/mysql-workbench-schema-exporter#139]
The error message is: Unknown data type "com.mysql.rdbms.mysql.datatype.time_f".

The problem is fixed when I change the following line in DatatypeConverterInterface.php:
    const DATATYPE_TIME                = 'com.mysql.rdbms.mysql.datatype.time_f';   //added _f at end

I suspect that it's broken because the new version of mysql supports fractional times and dates, so perhaps they changed the datatype name (I'm not knowledgeable enough to know whether this is the correct solution, or how you would handle differing versions of mysql workbench).

**Comment by tohenk** [comment]
Fixed in 866e2b8593ec4bc2970f7f76fe74cadbeae2febc.

**Comment by JDruery** [comment]
Thanks, that was fast!
