### ISSUE TITLE
New Model Comment feature request

### ISSUE THREAD

**Issue by JDruery** [johmue/mysql-workbench-schema-exporter#140]
Could there be a new Model Comment Behavior that could handle adding arbitrary annotations? I'm not familiar with all of the schemas, but my use case would be to add one or more annotations to configure Doctrine2 extensions. If I could put a comment on a column or table like:

{d:annotation}
  @Gedmo\TreeParent
{/d:annotation}

Then the result in the entity would look like:
    /**
     * @Gedmo\TreeParent
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     */
Where the first item is added from the model comment and the rest are automatic.

The benefit to this is that I would not need to manually edit the entities after generating them. So in future if I make a change to the ER diagram, I can simply regenerate all entities without have to manually add in changes again. Perhaps I'm missing something and there already is a way to do this.

**Comment by piotr-janik** [comment]
Just try to put "@Gedmo\TreeParent" in a comment, with no additional tags.

**Comment by rvock** [comment]
This is already possible with normal comments. See #148
