### ISSUE TITLE
Feature Request: Add additional annotations as comments in diagram

### ISSUE THREAD

**Issue by victoriousgaming** [johmue/mysql-workbench-schema-exporter#148]
Thank you for your efforts, this project has been incredibly useful to me in the past

In order to use Docrtine 2 Plugins, additional annotations needed to be added to many of the columns in a entity.

For instance:

/**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

If you could add your own annotations to a column in the comments on the diagram it would help using Doctrine 2 plugins.

However it seemed possible from reading the documentation that this is support already, just by adding a comment to a column -- could you clarify if this is possible?

I do not have an ENV set up at the moment to test the above but will shortly.

Thank you very much.

Will Ferrer

**Comment by rvock** [comment]
This is already possible using comments in MySQL-Workbench:
![customannotations](https://cloud.githubusercontent.com/assets/209159/12072151/58d16f06-b0d2-11e5-9776-ff2dc7373fda.png)

This generates the following code:
```php
/**
 * @Gedmo\Timestampable(on="update")
 *
 * @ORM\Column(type="datetime", nullable=true)
 */
protected $created_at;
```

You can use newlines for multiple annotations. the * infront of the comment line is added automatically
